apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 5m
  path: "./adguard"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
