apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karl-blog
  namespace: flux-system
spec:
  interval: 5m
  path: "./blog"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
