apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-daemon
  namespace: flux-system
spec:
  interval: 5m
  path: "./cloudflare-daemon"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
