apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 5m
  path: "./home-assistant"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
