apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: speedtest-exporter
  namespace: flux-system
spec:
  interval: 5m
  path: "./speedtest-exporter"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
