apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kepler
      version: "0.5.7"
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: flux-system