apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kepler
  namespace: flux-system
spec:
  interval: 5m
  url: https://sustainable-computing-io.github.io/kepler-helm-chart
