kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-root
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: home-assistant-config-root-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-root-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/home-assistant-config"