apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          imagePullPolicy: Always
          args: ["--work-dir", "/opt/adguardhome/work", "--config", "/opt/adguardhome/conf/AdGuardHome.yaml"]
          ports:
            - containerPort: 53 #dns
              name: dns
              protocol: UDP
            - containerPort: 3000 #initial setup
              name: http-initial
            - containerPort: 80 #web gui
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-data
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/adguard"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-csi"
  volumeName: adguard-pv
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: default
spec:
  selector:
    app: adguard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-initial
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
  type: LoadBalancer
  loadBalancerIP: <your-loadbalancer-ip>
