apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-blog-deployment
  labels:
    app: karl-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karl-blog
  template:
    metadata:
      labels:
        app: karl-blog
    spec:
      imagePullSecrets:
      - name: <your-registry-secret>
      containers:
      - name: karl-blog-container
        image: <your-registry>/blog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80